image: mono:latest

stages:
  - build

before_script:
  - nuget source Add -Name "TCAdmin" -Source "https://gitlab.com/api/v4/projects/17210103/packages/nuget/index.json"
  - nuget restore -NonInteractive
  - nuget install TCAdmin

release:
  stage: build
  only:
    - master
  artifacts:
    paths:
      - build/release/TCAdminWrapper.dll
  script:
    # The output path is relative to the position of the csproj-file
    - msbuild /p:Configuration="Release" /p:Platform="Any CPU"
      /p:OutputPath="./../../build/release/" "/TCAdminWrapper.csproj"